name: build caddy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
permissions:
  actions: read
  contents: read
  packages: write
jobs:
  build:
    name: Build: Caddy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for multiarch build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        uses: docker/build-push-action@v5
        id: build
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/zingyawesome/caddy:latest
          push: true
